### ISSUE TITLE
No Bar

### ISSUE THREAD

**Issue by Simiea** [pbone64/ArmorToughnessBar#1]
Armour toughness bar is not there. Is there something I am doing wrong?

**Comment by pbone64** [comment]
Sorry for the super late response - I'm just getting back to this project. The bar only appears if you have any armour toughness (i.e. from netherite or diamond armor).

If you have armour toughness and the bar still isn't showing up - are you connected to a server, and what other mods do you have installed?

No worries if you can't answer these questions. I understand that this issue was made close to a year ago.

**Comment by Simiea** [comment]
Yeah I think I fixed it, thanks for reaching out anyhow
